### ISSUE TITLE
你好，请问报错原因

### ISSUE THREAD

**Issue by SakiMJ** [xyk953651094/SkyNewTab-React#17]
本地start之后，页面过一会就会报错 
![201695609289_ pic](https://github.com/xyk953651094/SkyNewTab-React/assets/31894246/32a1f1cb-015b-4297-aea4-34b734d9a21b)

**Comment by xyk953651094** [comment]
您好，我这边无法复现您遇到的问题，我调试的时候没有遇到这个问题，但我后面会注意这个问题的。就目前来说 classList 出现在 clockComponent.tsx 和 wallpaperComponent.tsx 里，如有需要您可以自行调试一下。如果您格隆的是 main 分支代码，可以重新尝试克隆 xyk 分支，或者再次克隆最新的代码，试试看还有没有这个问题。

最后说句题外话，我是菜鸟一只，没有设计没有美工没有测试，一个人业余时间边学习边开发，所以这个产品还有很多方面需要完善，也没有办法为您及时提供专业的技术支持，深感抱歉。
